- name: vars in playbook
  gather_facts: false
  hosts: local_host
  connection: local_host
  vars:
    name: "murali"
    age: 2002
  var_files:
    - vars.yaml
  var_prompt:
    name: prof
    prompt: "enter the prof"
  tasks:
    - name: message the server
      vars:
        gender: "male"
      ansible.builtin.debug:
        msg: "{{ name }} and {{ age }} and {{ country }} and {{ prof }} and {{ course }} and {{ gender }} and {{ loc }}"
