- name: playbook 1
  gather_facts: false
  hosts: web
  connection: local
  tasks:
    - name: string and number data
      vars:
        name: "murali, this is string"
        age: 200
    - name: list and map
      ansible.built.debug:
        msg: "{{ name }}"
      loop:
        - list 1
        - list 2
    - name: boolean data
      vars:
        ismale: true
      ansible.built.debug:
        msg: "{{ ismale }}"
