- name: vars in playbook
  gather_facts: false
  hosts: web
  connection: local
  vars:
    name: "murali"
    age: 2002
  vars_files:
    - vars.yaml
  vars_prompt:
    name: prof
    prompt: "enter the prof"
  tasks:
    - name: message the server
      vars:
        gender: "male"
      ansible.builtin.debug:
        msg: "{{ name }} and {{ age }} and {{ country }} and {{ prof }} and {{ course }} and {{ gender }} and {{ loc }}"
